model:
  latent_dim: 20
  encoder_channels: [32, 64, 128]
  decoder_channels: [128, 64, 32]
  kernel_size: 3
  stride: 2
  padding: 1
  
training:
  batch_size: 128
  learning_rate: 0.0001
  num_epochs: 50
  beta: 1.0
  beta_schedule: "linear"
  beta_start: 0.0
  beta_end: 1.0
  beta_warmup_epochs: 10
  reconstruction_loss: "bce"
  gradient_clip: 1.0
  
optimizer:
  type: "adam"
  weight_decay: 0.0
  betas: [0.9, 0.999]
  
scheduler:
  type: "cosine"
  min_lr: 0.00001
  warmup_epochs: 5
  
data:
  data_dir: "./data"
  num_workers: 4
  pin_memory: true
  train_val_split: 0.9
  
logging:
  log_interval: 100
  save_interval: 5
  tensorboard: true
  log_dir: "./outputs/logs"
  
checkpoint:
  save_dir: "./outputs/checkpoints"
  save_best: true
  save_last: true
  resume: null
  
visualization:
  num_samples: 16
  fig_size: [8, 8]
  save_reconstructions: true
  save_interval: 5
  output_dir: "./outputs/visualizations"
  
interpolation:
  num_steps: 60
  fps: 10
  digit_pairs: [[0, 1], [3, 8], [4, 9], [2, 7], [5, 6]]
  num_examples_per_pair: 3
  output_dir: "./outputs/visualizations"
  
seed: 42
device: "cuda"